name: Python CI/CD

on:
  push:
    branches: [feature-logging]
  pull_request:
    branches: [feature-logging]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install flake8 pytest flask
      
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exit-zero
          flake8 . --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Run tests
        run: pytest || true
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/python-app:latest
      
      - name: Deploy to EC2 with SSH
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USERNAME }}
          DOCKER_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/python-app:latest
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          # SSH commands to deploy
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST "
            docker pull $DOCKER_IMAGE
            docker stop python-app || true
            docker rm python-app || true
            docker run -d --name python-app -p 80:5000 $DOCKER_IMAGE
            docker ps
          "
          
          # Clean up
          rm -f private_key.pem