name: Python CI/CD

on:
  push:
    branches: [feature-logging]
  pull_request:
    branches: [feature-logging]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install test dependencies
        run: |
          pip install flake8 pytest
      
      - name: Lint with flake8
        run: flake8 .
      
      - name: Run tests
        run: pytest
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/python-app:latest
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/python-app:latest
            docker stop python-app || true
            docker rm python-app || true
            docker run -d --name python-app -p 80:5000 ${{ secrets.DOCKER_HUB_USERNAME }}/python-app:latest